apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-configmap
data:
  index.html: |
    <html>
      <head>
        <title>App1</title>
      </head>
      <body>
        <p>Welcome to app1</p>
      </body>
    </html>