apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-pod
  template:
    metadata:
      labels:
        app: app1-pod
    spec:
      containers:
      - name: app1
        image: nginx:alpine
        ports:
          - containerPort: 80
        volumeMounts:
          - name: vol-app1
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: vol-app1
        configMap:
          name: app1-configmap
