apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-configmap
data:
  index.html: |
    <html>
      <head>
        <title>App2</title>
      </head>
      <body>
        <p>Welcome to App2</p>
      </body>
    </html>

