apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-configmap
data:
  index.html: |
    <html>
      <head>
        <title>App3</title>
      </head>
      <body>
        <p>Welcome to App3</p>
      </body>
    </html>